### ISSUE TITLE
Usability of cli commands

### ISSUE THREAD

**Issue by root-aza** [cycle/bootstrap#1]
Хотелось бы что пакет был более юзабельным (Т.е команды).

В свободное время пилю бандл для sf и наткнулся на проблему,чтобы завести команды надо пол фрейма spiral поднять,а этого делать не хочеться. А пилить свои команды с нуля, ну такое ...

**Comment by wolfy-j** [comment]
Ммммм, наши команды совместимы с Symfony, разве не достаточно их просто зарегать в Console Kernel?

**Comment by root-aza** [comment]
@wolfy-j  нет.Надо подгрузить половина вашего фрейма.

**Comment by wolfy-j** [comment]
ОК, будет время поправим. Либо кидайте ПР
